# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(719, 650)
        self.outputBox = QtWidgets.QGroupBox(Dialog)
        self.outputBox.setGeometry(QtCore.QRect(10, 380, 701, 201))
        self.outputBox.setObjectName("outputBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.outputBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 681, 151))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.md4Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.md4Label.setObjectName("md4Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.md4Label)
        self.md4Output = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(11)
        self.md4Output.setFont(font)
        self.md4Output.setReadOnly(True)
        self.md4Output.setObjectName("md4Output")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.md4Output)
        self.md5Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.md5Label.setObjectName("md5Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.md5Label)
        self.md5Output = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(11)
        self.md5Output.setFont(font)
        self.md5Output.setReadOnly(True)
        self.md5Output.setObjectName("md5Output")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.md5Output)
        self.sha1Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.sha1Label.setObjectName("sha1Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sha1Label)
        self.sha1Output = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(11)
        self.sha1Output.setFont(font)
        self.sha1Output.setReadOnly(True)
        self.sha1Output.setObjectName("sha1Output")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sha1Output)
        self.sha256Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.sha256Label.setObjectName("sha256Label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.sha256Label)
        self.sha256Output = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(11)
        self.sha256Output.setFont(font)
        self.sha256Output.setReadOnly(True)
        self.sha256Output.setObjectName("sha256Output")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sha256Output)
        self.hmacLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.hmacLabel.setObjectName("hmacLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.hmacLabel)
        self.hmacOutput = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(11)
        self.hmacOutput.setFont(font)
        self.hmacOutput.setReadOnly(True)
        self.hmacOutput.setObjectName("hmacOutput")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.hmacOutput)
        self.processInputButton = QtWidgets.QToolButton(Dialog)
        self.processInputButton.setGeometry(QtCore.QRect(520, 600, 191, 43))
        self.processInputButton.setObjectName("processInputButton")
        self.infoLabel = QtWidgets.QLabel(Dialog)
        self.infoLabel.setGeometry(QtCore.QRect(20, 600, 421, 31))
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")
        self.keyboardBox = QtWidgets.QGroupBox(Dialog)
        self.keyboardBox.setGeometry(QtCore.QRect(10, 10, 701, 161))
        self.keyboardBox.setObjectName("keyboardBox")
        self.hexKeyboardCheckBox = QtWidgets.QCheckBox(self.keyboardBox)
        self.hexKeyboardCheckBox.setGeometry(QtCore.QRect(570, 130, 123, 35))
        self.hexKeyboardCheckBox.setObjectName("hexKeyboardCheckBox")
        self.keyboardInputText = QtWidgets.QPlainTextEdit(self.keyboardBox)
        self.keyboardInputText.setGeometry(QtCore.QRect(10, 40, 681, 91))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.keyboardInputText.setFont(font)
        self.keyboardInputText.setObjectName("keyboardInputText")
        self.fileBox = QtWidgets.QGroupBox(Dialog)
        self.fileBox.setGeometry(QtCore.QRect(10, 179, 701, 81))
        self.fileBox.setObjectName("fileBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.fileBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 681, 45))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.fileLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.fileLayout.setContentsMargins(0, 0, 0, 0)
        self.fileLayout.setObjectName("fileLayout")
        self.filenameLine = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.filenameLine.setClearButtonEnabled(True)
        self.filenameLine.setObjectName("filenameLine")
        self.fileLayout.addWidget(self.filenameLine)
        self.browseFileButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.browseFileButton.setObjectName("browseFileButton")
        self.fileLayout.addWidget(self.browseFileButton)
        self.hexFileCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.hexFileCheckBox.setObjectName("hexFileCheckBox")
        self.fileLayout.addWidget(self.hexFileCheckBox)
        self.hmacBox = QtWidgets.QGroupBox(Dialog)
        self.hmacBox.setGeometry(QtCore.QRect(10, 260, 701, 121))
        self.hmacBox.setObjectName("hmacBox")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.hmacBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 681, 79))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hmacLabels = QtWidgets.QVBoxLayout()
        self.hmacLabels.setObjectName("hmacLabels")
        self.claveLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.claveLabel.setObjectName("claveLabel")
        self.hmacLabels.addWidget(self.claveLabel)
        self.hashLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.hashLabel.setObjectName("hashLabel")
        self.hmacLabels.addWidget(self.hashLabel)
        self.horizontalLayout.addLayout(self.hmacLabels)
        self.hmacFields = QtWidgets.QVBoxLayout()
        self.hmacFields.setObjectName("hmacFields")
        self.keyLayout = QtWidgets.QHBoxLayout()
        self.keyLayout.setObjectName("keyLayout")
        self.keyLine = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.keyLine.setFont(font)
        self.keyLine.setObjectName("keyLine")
        self.keyLayout.addWidget(self.keyLine)
        self.hexKeyCheckbox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.hexKeyCheckbox.setObjectName("hexKeyCheckbox")
        self.keyLayout.addWidget(self.hexKeyCheckbox)
        self.hmacFields.addLayout(self.keyLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hashComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.hashComboBox.setObjectName("hashComboBox")
        self.hashComboBox.addItem("")
        self.hashComboBox.addItem("")
        self.hashComboBox.addItem("")
        self.hashComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.hashComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.hmacFields.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.hmacFields)
        self.hmacBox.raise_()
        self.outputBox.raise_()
        self.processInputButton.raise_()
        self.infoLabel.raise_()
        self.keyboardBox.raise_()
        self.fileBox.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Funciones hash"))
        self.outputBox.setTitle(_translate("Dialog", "Salida"))
        self.md4Label.setText(_translate("Dialog", "MD4"))
        self.md5Label.setText(_translate("Dialog", "MD5"))
        self.sha1Label.setText(_translate("Dialog", "SHA-1"))
        self.sha256Label.setText(_translate("Dialog", "SHA-256"))
        self.hmacLabel.setText(_translate("Dialog", "HMAC"))
        self.processInputButton.setText(_translate("Dialog", "Procesar"))
        self.keyboardBox.setTitle(_translate("Dialog", "Entrada por teclado"))
        self.hexKeyboardCheckBox.setText(_translate("Dialog", "Hexadecimal"))
        self.fileBox.setTitle(_translate("Dialog", "Entrada por archivo"))
        self.browseFileButton.setText(_translate("Dialog", "Buscar archivo"))
        self.hexFileCheckBox.setText(_translate("Dialog", "Hexadecimal"))
        self.hmacBox.setTitle(_translate("Dialog", "Opciones HMAC"))
        self.claveLabel.setText(_translate("Dialog", "Clave"))
        self.hashLabel.setText(_translate("Dialog", "Hash"))
        self.hexKeyCheckbox.setText(_translate("Dialog", "Hexadecimal"))
        self.hashComboBox.setItemText(0, _translate("Dialog", "MD4"))
        self.hashComboBox.setItemText(1, _translate("Dialog", "MD5"))
        self.hashComboBox.setItemText(2, _translate("Dialog", "SHA-1"))
        self.hashComboBox.setItemText(3, _translate("Dialog", "SHA-256"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
